style: new mobile text-wrap & breadcrumbs
csunibo/dynamik pull request #141
Opened 2023-10-30 18:39 UTC by ali-benny

Fix: su mobile ora tutti i text si wrappano nel titolo della page del CdL
Fix: su mobile ora tutti i text nella home restano centrati
Style: creato bottone per mostrare i breadcrumbs su mobile nella `[zfile=dir]/+page.svelte`

**Style: modificata visualizzazione del link-logo a github**
L'ho spostato dal breadcrumbs in modo che sia semrpe accessibile e l'ho allineato con il bottone del `fuzzyfinder` in un `navbar-end`

NB: @csunibo/frontend dite voi se approvate questa cosa, è l'ultimo commit possiamo toglierlo senza problemi se non vi piace nel caso

----
Come spiegato qui https://github.com/csunibo/dynamik/issues/126#issuecomment-1785805527 dove ci sono anche qualche screen

2023-10-30 19:17 UTC, VaiTon requested changes

2023-10-30 19:17 UTC, VaiTon commented on .vscode/settings.json
Questo eviterei di committarlo

2023-10-30 19:17 UTC, VaiTon commented on src/routes/[...dir]/[zfile=dir]/+page.svelte
> +		return () => {
Non è necessario ritornare una funzione. Poi quando viene utilizzata basta passare
```svelte
on:click={mobileBreadcrumb}
```

2023-10-30 19:17 UTC, VaiTon commented on src/routes/[...dir]/[zfile=dir]/+page.svelte
> +			if (breadcrumb) {
```suggestion
			if (breadcrumb != null) {
```

2023-10-30 19:17 UTC, VaiTon commented on src/routes/[...dir]/[zfile=dir]/+page.svelte
> +			if (title) {
```suggestion
			if (title != null) {
```

2023-10-30 19:17 UTC, VaiTon commented on src/routes/[...dir]/[zfile=dir]/+page.svelte
> +			const breadcrumb = document.querySelector('.breadcrumbs');
Al posto di questa sintassi super javascript vanilla magari conviene utilizzare svelte. Cosa volevi fare? Dove si trova il componente con `.breadcrumbs`? In generale puoi usare un `bind:this`[^1] per bindare un elemento HTML ad una variabile JS e poi chiamarla direttamente. Esempio:

```html
<div class="..." bind:this={interesting_div}> ...</div>
```
```svelte
let interesting_div: HTMLElement;
function x(...) {
  interesting_div.classList.toggle("...");
}
```

[^1]: https://svelte.dev/tutorial/bind-this

2023-10-30 19:19 UTC, ali-benny commented on .vscode/settings.json
ops me lo aggiunge sempre, chiedo scusa

2023-10-30 19:20 UTC, ali-benny commented on src/routes/[...dir]/[zfile=dir]/+page.svelte
> +			const breadcrumb = document.querySelector('.breadcrumbs');
coooooooos? magia ✨

2023-11-01 11:01 UTC, foxyseta commented on .vscode/settings.json
@ali-benny puoi aggiungerlo al .gitignore globale sulla tua macchina.

2023-11-01 17:04 UTC, VaiTon commented on src/routes/[...dir]/[zfile=dir]/+page.svelte
> +
Sorry se rompo. Potresti addirittura usare una var del tipo `let breadcrumbActivated = false` e bindare questo, senza i due elementi

2023-11-02 11:12 UTC, ali-benny commented on src/routes/[...dir]/[zfile=dir]/+page.svelte
> +
Vai tranquillo, piuttosto scusami tu ahhahah non sono molto pratica di svelte e sinceramente non ho ben capito come bindare una var booleana. Intendi fare un'unico if su `let breadcrumbActivated`?

2023-11-03 09:59 UTC, VaiTon commented on src/routes/[...dir]/[zfile=dir]/+page.svelte
> +
```
let breadcrumbActivated = false;
function mobileBreadcrumb() {
	breadcrumbActivated = !breadcrumbActivated;
}

```
nell'HTML
```
<div ...
class:hidden={breadcrumbActivated}
...
/>
```

2023-11-06 16:18 UTC, VaiTon commented
@ali-benny io ancora vedo una cosa del genere con l'emulatore di Chrome

![image](https://github.com/csunibo/dynamik/assets/12072630/3026f02a-6262-4d0c-8ad5-91f03ae98fac)

2023-11-06 16:37 UTC, ali-benny commented
> @ali-benny io ancora vedo una cosa del genere con l'emulatore di Chrome
> 
> ![image](https://user-images.githubusercontent.com/12072630/280775719-3026f02a-6262-4d0c-8ad5-91f03ae98fac.png)

strano, domani vedo di fixare

2023-11-07 16:41 UTC, ali-benny commented
> > @ali-benny io ancora vedo una cosa del genere con l'emulatore di Chrome
> strano, domani vedo di fixare

Mi ero scordata di aggiungere il file al commit -.-

2023-11-11 12:00 UTC, ali-benny commented
@VaiTon bump

2023-11-13 12:25 UTC, VaiTon approved these changes

2023-11-13 12:25 UTC, VaiTon commented
@ali-benny ci sono conflitti

2023-11-13 13:06 UTC, ali-benny commented
> @ali-benny ci sono conflitti

a me non risultano

2023-11-14 20:30 UTC, merged