Fix/500 error dir
csunibo/dynamik pull request #153
Opened 2023-11-10 11:02 UTC by ali-benny

This close #151 

Colpa di una variabile che non si aggiornava, ora passo ogni volta il contenuto della variabile.

2023-11-10 21:10 UTC, VaiTon commented on src/lib/components/Line.svelte
> +	// let base = $page.url.pathname.split('?')[0];
basta mettere 

```
$: base = ...
```

e lasciare tutto il resto uguale.

2023-11-10 21:10 UTC, VaiTon commented on src/lib/components/Line.svelte
> +				href="{$page.url.pathname}/{data.name}?{$page.url.searchParams}"
Lo split siamo sicuri non serve?

2023-11-10 21:14 UTC, ali-benny commented on src/lib/components/Line.svelte
> +	// let base = $page.url.pathname.split('?')[0];
Lmao oks

2023-11-10 21:14 UTC, ali-benny commented on src/lib/components/Line.svelte
> +				href="{$page.url.pathname}/{data.name}?{$page.url.searchParams}"
Ho fatto delle prove e sembra che non prenda i searchParams all'interno del pathname

2023-11-12 12:01 UTC, VaiTon requested changes

2023-11-12 12:01 UTC, VaiTon commented on .vscode/settings.json
Togliamo questo dalla PR pls

2023-11-12 12:14 UTC, VaiTon commented
Ho fatto io in #156

2023-11-12 12:14 UTC, closed without merging

2023-11-12 12:58 UTC, ali-benny commented on .vscode/settings.json
Ops si