feat: cookie default view #163
csunibo/dynamik pull request #167
Opened 2023-11-18 21:29 UTC by Flecart

2023-11-19 15:07 UTC, VaiTon reviewed
Solamente un appunto. Per il resto tutto OK per me 👍

2023-11-19 15:07 UTC, VaiTon commented on src/routes/+page.svelte
> +	let showFeature = true;
Qui il problema è che ogni volta che aggiorno la pagina mi ricompare. Dovremmo salvare qualcosa nel local storage che ci permette di conservare la scelta :)

2023-11-20 10:25 UTC, ali-benny requested changes

2023-11-20 12:26 UTC, Flecart commented on src/routes/+page.svelte
> +					class="underline text-blue-600 hover:text-blue-800 visited:text-purple-600"
È viola solo se lo hai visitato

2023-11-20 12:27 UTC, Flecart commented on src/routes/+page.svelte
> +	<div class="bg-blue-500 text-white p-4">
Quali sono? Questo colore lo ho scelto perché sta bene sia in dark che light mode.

2023-11-20 12:46 UTC, ali-benny commented on src/routes/+page.svelte
> +	<div class="bg-blue-500 text-white p-4">
ogni tema di daisyui ha un pattern unico di colori:
https://daisyui.com/docs/colors/

nel nostro caso userei un `secondary` [per avere un colore carico] o anche `accent`... vedi tu dato che i colori etichettati con `info` sono opzionali

2023-11-22 10:38 UTC, VaiTon commented on src/routes/+page.svelte
> +	};
Usiamo sempre il componente svelte localstorage se possibile, così possiamo astrarre dall'implementazione

2023-12-06 11:27 UTC, Flecart commented on src/routes/+page.svelte
> +	let showFeature = false;
Sì, perché altrimenti refreshando la pagina viene sempre il banner, così di default non ha banner.

2023-12-08 07:32 UTC, Flecart commented
@VaiTon riusciresti a fixare te e mergiare, perfavore :D?

2023-12-10 15:45 UTC, VaiTon approved these changes

2023-12-11 09:05 UTC, ali-benny approved these changes

2023-12-11 09:05 UTC, ali-benny commented on src/routes/+page.svelte
> +				selezionare il tuo corso preferito! Ogni volta che accedi verrai subito portato al tuo corso
più che "ogni volta che accedi" metterei "All'apertura" o qualcosa del genere, ma va bene lo stesso ahahah

2023-12-12 21:24 UTC, merged