feat: todo file check
csunibo/dynamik pull request #200
Opened 2023-12-20 10:35 UTC by ali-benny

Aggiunta la possibilità di "spuntare" un file.
Se nella pagina corrente è presente un file come "done", verrà abilitato il pulsante _Clean_ per pulire e togliere lo status "done" da tutti i file della pagina corrente.

2023-12-20 10:47 UTC, ali-benny commented
![image](https://github.com/csunibo/dynamik/assets/74602443/c024a2ea-85b2-4c68-bb2f-36fd0f724499)

che cazzo vuole il formatter non so...

2023-12-20 19:17 UTC, VaiTon requested changes

2023-12-20 19:17 UTC, VaiTon commented on src/lib/components/Line.svelte
> +	}
Perché non lo collassiamo in questo?

```suggestion
	$: isDone = $doneStatusPage ? getDoneStatus($page.url + '/' + data.name) : false;
```

2023-12-20 19:17 UTC, VaiTon commented on src/lib/components/Line.svelte
> +	} from '$lib/todo-file';
Please gli import all'inizio del file :)

2023-12-20 19:17 UTC, VaiTon commented on src/lib/components/Line.svelte
> +			$doneStatusPage = done_page;
Penso si possa collassare in 
```
doneStatusPage.set(...);
```

2023-12-20 19:17 UTC, VaiTon commented on src/lib/todo-file.ts
Abbiamo già una dipendenza su `svelte-localstorage`. Perchè re-implementare da capo le sue meccaniche?

2023-12-20 19:17 UTC, VaiTon commented on src/routes/[...dir]/[zfile=dir]/+page.svelte
> +	import { cleanDonePage, getDoneStatusPage, doneStatusPage } from '$lib/todo-file'; //Todo file
```suggestion
	import { cleanDonePage, getDoneStatusPage, doneStatusPage } from '$lib/todo-file';
```

2023-12-20 19:17 UTC, VaiTon commented on src/routes/[...dir]/[zfile=dir]/+page.svelte
> +	$: isDone = getDoneStatusPage($page.url.toString());
Perchè `isDone` è definito due volte? La seconda è reattiva e non ha necessità della prima (ma non capisco la `subscribe` su `doneStatusPage`)

2023-12-20 19:21 UTC, ali-benny commented on src/lib/components/Line.svelte
> +	} from '$lib/todo-file';
ahhahhah sisi scusaaa era che ci stavo lavorando ups

2023-12-20 19:22 UTC, ali-benny commented on src/routes/[...dir]/[zfile=dir]/+page.svelte
> +	$: isDone = getDoneStatusPage($page.url.toString());
senza subscribe non si aggiornava, faccio delle prove di nuovo...

2023-12-20 19:25 UTC, ali-benny commented on src/lib/todo-file.ts
eeeeeeeeeeeee ops non avevo visto

2023-12-20 19:31 UTC, ali-benny commented on src/routes/[...dir]/[zfile=dir]/+page.svelte
> +	$: isDone = getDoneStatusPage($page.url.toString());
sì, confermo la subscribe gli serve per aggiornare la ui istantaneamente tra Line e page

2023-12-20 19:33 UTC, VaiTon commented on src/routes/[...dir]/[zfile=dir]/+page.svelte
> +	$: isDone = getDoneStatusPage($page.url.toString());
Devi inserire $doneStatusPage come parametro della funzione, altrimenti svelte non sa che la variabile `isDone` è reattiva rispetto a `$doneStatusPage`. In generale se dichiari una variabile reattiva con `$:` deve essere `readonly` per te.

2023-12-20 19:36 UTC, VaiTon commented on src/lib/todo-file.ts
> +	return localStorage.getItem(fileName) === 'done';
Qui le cose sono due:
- al posto di creare un entry nel `localStorage` per ogni file ne creiamo una di tipo array o dizionario in cui salviamo quelli spuntati
- prefissiamo tutte le entry con qualcosa di comune

L'utilizzo di quel `doneStatusPage` non ho capito qual è sinceramente.

2023-12-20 19:36 UTC, ali-benny commented
comunque non capisco perchè dia sto errore con vercel 
![image](https://github.com/csunibo/dynamik/assets/74602443/ec927d12-80f5-46ea-b605-07704f3828fd)

mentre in locale va tutto... Tra l'altro non ho toccato nulla su UpperCase 😢 🥺

2023-12-20 19:38 UTC, ali-benny commented on src/lib/todo-file.ts
> +	return localStorage.getItem(fileName) === 'done';
nooooooooo piango, okay speravo andasse bene anche così... Domani sera se riesco guardo

`doneStatusPage ` mi serve per syncare Line.svelte e page.svelte perchè se uno spuntava qualcosa non spownava fuori il button

2023-12-20 19:39 UTC, ali-benny commented on src/routes/[...dir]/[zfile=dir]/+page.svelte
> +	$: isDone = getDoneStatusPage($page.url.toString());
mhhh okksi, comunque ho lasciato solo quella reattiva

2023-12-20 20:29 UTC, ali-benny commented on src/lib/todo-file.ts
> +	return localStorage.getItem(fileName) === 'done';
> - al posto di creare un entry nel `localStorage` per ogni file ne creiamo una di tipo array o dizionario in cui salviamo quelli spuntati

In realtà gli passo solo i file che vengono spuntati non tutti i file, e come identificativo passato l'URL in modo che fosse legato alla pagina in cui era. Se preferisci possiamo passare solo il percorso tipo breadcrumbs degree/teaching/dir/file

2023-12-31 13:32 UTC, VaiTon commented
@ali-benny can I review?

2023-12-31 13:42 UTC, ali-benny commented
@VaiTon se passa i check ora si

2023-12-31 13:43 UTC, ali-benny commented
cmq abbiamo problemi con url [che non dipendono in teoria da questa pr] 
![image](https://github.com/csunibo/dynamik/assets/74602443/f39a7e37-9caa-4614-8f78-264f0142812f)
ci mette un `/` prima dei `searchParams`

2024-01-08 11:02 UTC, ali-benny commented
@VaiTon riusciresti a guardarci? 🥺

2024-01-23 16:46 UTC, ali-benny commented
@VaiTon purtroppo è tornato fuori un bug: il primo elemento in ogni teachings se spuntato da in una qualche sub dir è automaticamente spuntato in tutte le altre sub dir... Mi era già successo ed era per un qualche problema di sincronizzazione tra data.url e doneFiles

2024-01-24 14:23 UTC, VaiTon commented
@ali-benny dovrei aver sistemato :)

2024-01-24 14:48 UTC, ali-benny commented
@VaiTon ora il clean btn spawna solo se è done il readme loooool 
mi dispiace ahhhaha stasera ci guardo appena riesco

2024-01-29 19:15 UTC, VaiTon commented
@ali-benny il pulsante per "pulire" compare solo quando sono tutti selezionati. Doveva per caso apparire quando _qualsiasi_ degli elementi è selezionato? Se è così ho pensato male io :P

2024-01-29 19:24 UTC, ali-benny commented
Si prima compariva quando almeno un elemento era spuntato all'interno della pagina corrente

2024-01-30 15:18 UTC, VaiTon commented
@ali-benny dovrebbe andare adesso!

2024-01-31 16:55 UTC, ali-benny commented
@VaiTon super ❤️ grazie milleee

2024-01-31 16:55 UTC, merged