Add dynamic page title and meta tag
csunibo/dynamik pull request #212
Opened 2024-01-19 12:48 UTC by ali-benny

2024-01-22 19:21 UTC, VaiTon commented
Sarebbe meglio ottenerlo dal file `statik.json`. L'ho fatto in locale ma non possiamo usare ancora `risorse.students. ...` perché ci sono problemi di CORS.

Punto a parte, siamo sicuri di voler proxare tutte le richieste?

2024-01-22 19:24 UTC, ali-benny commented
> Sarebbe meglio ottenerlo dal file `statik.json`.

Ah cavoli domani ci guardo allora
> L'ho fatto in locale ma non possiamo usare ancora `risorse.students. ...` perché ci sono problemi di CORS.

Oh shit, mi ero completamente dimenticata...
> Punto a parte, siamo sicuri di voler proxare tutte le richieste?

Non so dite voi

2024-01-22 19:56 UTC, VaiTon commented
> Non so dite voi

cc @samuelemusiani @foxyseta

2024-01-23 09:21 UTC, lucat1 commented
Ho capito cosa punta a fare la PR e concordo che sia meglio prendere magari il nome del file dal json o almeno usare la classe URL per sezionare il path.
Però non capisco il messaggio di eyad riguardo a CORS. È una cosa che possiamo risolvere aggiungendo gli header a risorse.students.cs.unibo.it o è una cosa tipo che prendiamo il file da github.io e loro non mettono gli header?
Fare il proxy da risorse sarebbe un po’ un problema in caso risorse andasse offline.

2024-01-24 14:26 UTC, VaiTon commented
@lucat1 sorry ho sbagliato PR, mi riferivo a #211

2024-01-24 14:28 UTC, VaiTon commented
@lucat1 hai ragione, mi sono fatto un ragionamento mentale io mentre provavo e non ho chiarito. Chiarisco nell'issue giusta. xD

2024-01-31 15:02 UTC, VaiTon requested changes

2024-01-31 15:02 UTC, VaiTon commented on src/routes/[...dir]/[zfile=generic]/+page.svelte
> +	$: title = url[url.length - 1].split('?')[0];
usando `let` non è reattivo, e al cambio di pagina rimane lo stesso. E' meglio creare una funzione `getTitle` e fare tutto il lavoro per poi usare una `$: title = getTitle(data.url)`

2024-01-31 18:37 UTC, VaiTon commented on src/routes/[...dir]/[zfile=generic]/+page.svelte
> +	}
Così non sono sicuro che svelte si accorga dei cambiamenti.
Io farei piuttosto:
```suggestion

	$: title = getTitle(data.url);

	function getTitle(url: string) {
	    const parts = url.split("/");
		return parts[parts.length - 1].split('?')[0];
	}
```

2024-01-31 19:27 UTC, ali-benny commented on src/routes/[...dir]/[zfile=generic]/+page.svelte
> +	}
okay in effetti ha senso!

2024-01-31 19:38 UTC, VaiTon approved these changes

2024-01-31 19:38 UTC, merged