chore: change ui
csunibo/dynamik pull request #35
Opened 2023-07-18 22:03 UTC by kocierik

Ho messo una bozza di una possibile idea

sono aperto a modifiche

2023-07-18 23:20 UTC, VaiTon commented
Non ho ancora guardato il codice, ma mi piace molto! Unica cosa, toglierei l'hover sulla navbar nella visualizzazione delle cartelle, visto che già c'è l'hover sui buttons ai lati

2023-07-18 23:24 UTC, VaiTon approved these changes
Oltre a quella osservazione tutto ok, thanks!

2023-07-19 05:11 UTC, lucat1 requested changes

2023-07-19 05:11 UTC, lucat1 commented on src/routes/[...dir]/[zfile=dir]/+page.svelte
> +	<div class="navbar flex bg-neutral-800 hover:bg-neutral-700 transition-colors duration-300 text-neutral-content rounded-box shadow-sm px-5 mb-5">
Anzi che usare esplicitamente i colori di tailwind è meglio usare gli alias di daisy per far funzionare il codice con tutti i temi.

2023-07-19 05:12 UTC, lucat1 commented
Ci sono anche altre occorrenze in cui non vengono usati i colori di daisy e andrebbero tutte sistemare.

2023-07-19 13:16 UTC, kocierik commented
ottimo sistemo e vi richiedo la review

2023-07-19 13:47 UTC, lucat1 approved these changes

2023-07-19 13:49 UTC, merged