feat: add mobile fuzzy finder
csunibo/dynamik pull request #59
Opened 2023-09-16 14:23 UTC by kocierik

2023-09-16 16:33 UTC, lucat1 requested changes
a parte la questione di quanto sia idiomatico il codice inline nell'html, mi preoccupa di più l'avere più refresh (motivo per cui penso fossero stati messi quegli if). Il secondo if che è stato tolto però mi pare che ci stia, tanto quell'assegnamento veniva fatto in ogni caso.

2023-09-16 16:33 UTC, lucat1 commented on src/routes/[...dir]/[zfile=dir]/+page.svelte
> +            <button class="lg:ml-2 p-2 rounded btn-ghost" title="ctrl + k" on:click|preventDefault={() => {
penso che sia più idiomatico mettere queste funzioni nella parte script su svelte.

2023-09-16 16:33 UTC, lucat1 commented on src/routes/[...dir]/[zfile=dir]/+page.svelte
> -			if (searchActive) searchActive = false;
forse gli if erano stati messi perchè  fare l'assegnamento ha comunque un sideeffect che avvia un update la pagina? @VaiTon

2023-09-16 18:49 UTC, VaiTon commented on src/routes/[...dir]/[zfile=dir]/+page.svelte
> -			if (searchActive) searchActive = false;
Si in teoria si, anche se non ti so dire se svelte controlli che la variabile sia stata effettivamente aggiornata (penso di no)

2023-09-16 18:49 UTC, VaiTon commented on src/routes/[...dir]/[zfile=dir]/+page.svelte
> +             🔍
Potresti aggiungere nel caso siamo su desktop questo componente che secondo me è molto carino: https://daisyui.com/components/kbd/

2023-09-17 07:55 UTC, kocierik commented on src/routes/[...dir]/[zfile=dir]/+page.svelte
> +             🔍
non si vede bene la distinzione del colore ma verrebbe così:
<img width="1167" alt="Screenshot 2023-09-17 at 09 53 38" src="https://github.com/csunibo/dynamik/assets/41591336/41a12758-494c-4315-86aa-64d20cfed0b0">

che ne dite?

2023-09-17 07:59 UTC, VaiTon commented on src/routes/[...dir]/[zfile=dir]/+page.svelte
> +             🔍
Mi piace! Forse lo renderei un minimo più arrotondato e stop

2023-09-17 08:03 UTC, kocierik commented on src/routes/[...dir]/[zfile=dir]/+page.svelte
> +             🔍
andata, pusho tutto e chiedo review

2023-09-17 08:09 UTC, VaiTon approved these changes

2023-09-17 08:10 UTC, merged

2023-09-17 08:10 UTC, VaiTon commented
Grazie! :tada: