chore: update type
csunibo/dynamik pull request #63
Opened 2023-09-19 07:47 UTC by kocierik

da approvare dopo:
https://github.com/csunibo/config/pull/4

2023-09-19 14:56 UTC, foxyseta requested changes
In `page.svelte` vedo in effetti un po' troppo copia e incolla, ma non so nulla di Svelte quindi non so se ci siano ragioni per non rendere il codice modulare in questo caso.

Approvo l'idea di forzare i corsi a scelta dopo quelli obbligatori all'interno dello stesso anno, anche se il file non li dovesse avere in fondo in futuro.

2023-09-19 15:03 UTC, kocierik commented
> In `page.svelte` vedo in effetti un po' troppo copia e incolla, ma non so nulla di Svelte quindi non so se ci siano ragioni per non rendere il codice modulare in questo caso.
> 
> Approvo l'idea di forzare i corsi a scelta dopo quelli obbligatori all'interno dello stesso anno, anche se il file non li dovesse avere in fondo in futuro.

anche a me non piace molto la struttura, se ci sono alternative sono favorevole

2023-09-20 01:12 UTC, foxyseta commented
Come per gli altri framework, ci sono i [componenti innestati](https://svelte.dev/examples/nested-components).

2023-10-01 10:11 UTC, kocierik commented
Ho fatto il merge del main e aggiunto il componente innestato

è rimasto un errore nei tipi che non riesco a sistemare

2023-10-01 11:08 UTC, VaiTon commented
@kocierik se possibile farei il filter in `+page.svelte` e passerei le due liste filtrate

2023-10-03 16:36 UTC, kocierik commented
dovrei aver fatto, se puo' andare mergio @csunibo/frontend

2023-10-03 17:28 UTC, VaiTon requested changes
Un po' di suggerimenti :)

2023-10-03 17:28 UTC, VaiTon commented on src/lib/teachings.ts
> +	optional: boolean;
```suggestion
	optional?: boolean;
```

2023-10-03 17:28 UTC, VaiTon commented on src/routes/ListTeaching.svelte
> +                                {#if teaching.telegram}
```suggestion
                                {#if teaching.telegram != null}
```

2023-10-03 17:28 UTC, VaiTon commented on src/routes/ListTeaching.svelte
> +    export let courses: TeachingYear[]
```suggestion
    export let years: TeachingYear[]
```

2023-10-03 17:28 UTC, VaiTon commented on src/routes/dash/[course]/+page.svelte
> +		<ListTeaching courses={filterCoursesOptional()[1]} activeYears={activeYears} base={base} optionalCourseViewTitle={true}/>
Non hai bisogno di passargli base, visto che lo puoi ottenere da svelte

2023-10-03 17:28 UTC, VaiTon commented on src/routes/ListTeaching.svelte
> +    export let optionalCourseViewTitle: boolean
Al posto di questo farei che ListTeaching esporta un title: string, e questo viene calcolato dal +page.svelte

2023-10-03 17:28 UTC, VaiTon commented on src/routes/dash/[course]/+page.svelte
> +		<ListTeaching courses={filterCoursesOptional()[1]} activeYears={activeYears} base={base} optionalCourseViewTitle={true}/>
Così chiami la funzione due volte, e la funzione scorre gli array due volte, quindi scorri gli array 4 volte. 

Al posto di questo metti nello <script> un
```
$: filteredCourses = filterCoursesOptional()
```
e poi qui metti un
```
courses={filteredCourses[0]} 
```
Addirittura, io ritornerei un oggetto, in modo tale da non usare roba tipo `[0]`, quindi
```
courses={filteredCourses.mandatory}
```

2023-10-03 17:39 UTC, VaiTon commented on src/routes/dash/[course]/+page.svelte
> +	}
Se proprio volessimo essere per l'efficienza computazionale questo array si potrebbe scorrere solamente una volta.

2023-10-03 21:51 UTC, kocierik commented on src/routes/dash/[course]/+page.svelte
> +	}
in questo caso penso che otterremmo comunque lo stesso costo computazionale poiche' dobbiamo iterare per ogni anno e per ogni materia ottenendo lo stesso limite superiore

Ho messo comunque un'altra funzione piu' carina ;)

2023-10-03 21:54 UTC, kocierik commented on src/routes/ListTeaching.svelte
> +    export let optionalCourseViewTitle: boolean
il title intendi inserirlo nella  dicitura (1,2,3)* anno (facoltativi)* ?

2023-10-03 21:56 UTC, VaiTon commented on src/routes/ListTeaching.svelte
> +    export let optionalCourseViewTitle: boolean
Si esatto! Interpolare la cosa in +page.svelte e li tenere solo un `title`

2023-10-03 22:05 UTC, kocierik commented on src/routes/ListTeaching.svelte
> +    export let optionalCourseViewTitle: boolean
apposto sistemato!

2023-10-04 00:57 UTC, foxyseta approved these changes

2023-10-04 11:03 UTC, VaiTon commented
@kocierik rebase pls :tada:

2023-10-04 11:30 UTC, kocierik commented
> @kocierik rebase pls 🎉

fatto fatto

2023-10-04 11:52 UTC, VaiTon approved these changes
Anche se la ricorsione mi fa veramente acido, per ora per me possiamo mergiare

2023-10-04 11:53 UTC, foxyseta approved these changes

2023-10-04 11:55 UTC, merged

2023-10-04 12:12 UTC, kocierik commented
Ho notato che nel deploy il filtro non funziona (vedi magistrale informatica) avete idee del perche'?

2023-10-04 12:19 UTC, VaiTon commented
@kocierik https://dynamik-git-chore-update-type-csunibo.vercel.app/dash/informatica-magistrale

Non te lo mostra con "1 anno facoltativi"?

2023-10-04 12:30 UTC, kocierik commented
> @kocierik https://dynamik-git-chore-update-type-csunibo.vercel.app/dash/informatica-magistrale
> 
> Non te lo mostra con "1 anno facoltativi"?

ops si, penso sia stato un problema di caching, c'è solo da sistemare la visualizzazione dell'icona per telegram perché da mobile è rotta ho notato